# Generated by Django 4.2.4 on 2023-08-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("idade", models.IntegerField()),
                ("teste", models.TextField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
